# This is a basic workflow to help you get started with Actions

name: Win Build

# Controls when the action will run. 
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    strategy:
            matrix:
                java: [16]
            fail-fast: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
            - uses: actions/checkout@v2
            - name: JDK ${{ matrix.java }}
              uses: actions/setup-java@v2
              with:
                  java-version: ${{ matrix.java }}
                  distribution: 'adopt'
            - name: Cache maven
              uses: actions/cache@v2
              with:
                  path: |
                      ~/.m2/repository/
                      work/Minecraft
                  key: ${{ runner.os }}-paper-2-${{ hashFiles('**/pom.xml') }}
                  restore-keys: ${{ runner.os }}-paper-2
            - name: Patch and build
              run: |
                  git config --global user.email "no-reply@github.com"
                  git config --global user.name "Github Actions"
                  ./paper build
            - name: Archive artifacts
              uses: actions/upload-artifact@v2
              if: success()
              with:
                name: Paper Build
                path: Paper-Server/*
